### ISSUE TITLE
Unexpected issue when using "infer" option

### ISSUE THREAD

**Issue by Licatia** [Gregor-Mendel-Institute/poolhap#1]
Hello, 

I'm trying to use poolhap to infer haplotypes frequencies from pooled-samples.
When i ran the infer option with halotypes matrix and associated pileup file, i encountered an issue that i do not understand : 

`java.lang.NumberFormatException:` For input string: "^]."
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at poolhap.Data.<init>(Data.java:68)
	at poolhap.EntrancePoolHap_hapknown.main(EntrancePoolHap_hapknown.java:74)
Exception in thread "main" java.lang.IllegalArgumentException: Degrees of freedom must be greater than 0
	at flanagan.analysis.Regression.linearGeneralMono(Regression.java:2781)
	at flanagan.analysis.Regression.linearGeneral(Regression.java:2767)
	at poolhap.Analysis.regress_hap_freqs(Analysis.java:20)
	at poolhap.EntrancePoolHap_hapknown.main(EntrancePoolHap_hapknown.java:7`

The first line shows an error with the first line of my pileup file, but it follow the standard format of pileup file, so what is the problem ? 
For the second error, what is the problem with degrees of freedom ? i can not change settings about it.

I'm sorry if solutions seems obvious but i do not understand. 

Thanks

**Comment by timeu** [comment]
Can you check if the pileup file or haplotypes matrix contains the  `^]` string somewhere ?

**Comment by Licatia** [comment]
the ^] string is a describer of the reads informations according to pileup format documentation (http://samtools.sourceforge.net/pileup.shtml ) and is present many times on my pileup file, but not in my matrix file.

**Comment by timeu** [comment]
Ok it could be that poolhap only works with an older Pileup format ?  I can try to contact the original author and see if he can help

**Comment by Licatia** [comment]
I don't know if significative changes had been done on pileup format. 
Ok thanks a lot

**Comment by Licatia** [comment]
Hello 
Did you contact the original author ? 
Thanks

**Comment by timeu** [comment]
@Licatia I talked to the author (Quan Long) and he said that this version of poolhap works only on an old version of the pileup format, but he will work on a new version that might actually use a much easier file input format. I think he doesn't have an ETA for that yet but he told me as soon as he has news, he will post in this issue.

**Comment by Licatia** [comment]
Ok thank you 
Do you know which version of pileup file is good for Poolhap's input ? 
I will try to test this one while waiting for the new release

**Comment by timeu** [comment]
Sorry for the late response. According to the Quan Long (main author), you need to use the samtools version that was used in the nature genetics 2013 paper. He also told me that you can contact him and he can help you with your specific data.

**Comment by Licatia** [comment]
No problem. 
I'll try this old version of samtools to generate my pileup file and try PoolHap with this one. 
If it does not work, i think i will Quan Long.
Thank you !
